import:
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-base-r4.1.yml
  - source: QubesOS/qubes-continuous-integration:R4.0/travis-vms-deb-r4.0.yml
  - source: QubesOS/qubes-continuous-integration:R4.0/travis-vms-deb-flavors-r4.0.yml
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-vms-deb-r4.1.yml
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-vms-deb-flavors-r4.1.yml

script: ~/qubes-builder/scripts/travis-build linux-template-builder
after_success:
 - ls -l ~/qubes-builder/qubes-src/linux-template-builder/rpm/noarch
jobs:
  include:
    # example "3.0 (quilt)" package, without upstream tarball
    - script: ~/qubes-builder/scripts/travis-build core-vchan-xen
      env: DISTS_VM=stretch USE_QUBES_REPO_VERSION=4.1 USE_QUBES_REPO_TESTING=1
    # example "3.0 (native)" package
    - script: ~/qubes-builder/scripts/travis-build linux-utils
      env: DISTS_VM=stretch USE_QUBES_REPO_VERSION=4.1 USE_QUBES_REPO_TESTING=1
    # example "3.0 (quilt)" package, with upstream tarball
    - script: ~/qubes-builder/scripts/travis-build python-u2flib-host
      env: DISTS_VM=stretch USE_QUBES_REPO_VERSION=4.1 USE_QUBES_REPO_TESTING=1
    # example ubuntu build
    - script: ~/qubes-builder/scripts/travis-build app-shutdown-idle
      env: DISTS_VM=xenial

    # example "3.0 (quilt)" package, without upstream tarball
    - script: ~/qubes-builder/scripts/travis-build core-vchan-xen
      env: DISTS_VM=stretch USE_QUBES_REPO_VERSION=4.1 USE_QUBES_REPO_TESTING=1 USE_DIST_BUILD_TOOLS=1
    # example "3.0 (native)" package
    - script: ~/qubes-builder/scripts/travis-build linux-utils
      env: DISTS_VM=stretch USE_QUBES_REPO_VERSION=4.1 USE_QUBES_REPO_TESTING=1 USE_DIST_BUILD_TOOLS=1
    # example "3.0 (quilt)" package, with upstream tarball
    - script: ~/qubes-builder/scripts/travis-build python-u2flib-host
      env: DISTS_VM=stretch USE_QUBES_REPO_VERSION=4.1 USE_QUBES_REPO_TESTING=1 USE_DIST_BUILD_TOOLS=1
    # example ubuntu build
    - script: ~/qubes-builder/scripts/travis-build app-shutdown-idle
      env: DISTS_VM=xenial USE_DIST_BUILD_TOOLS=1
